//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare_Eksame_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivingPlan
    {
        public int drivingID { get; set; }
        public int customerID { get; set; }
        public int employeeID { get; set; }
        public Nullable<System.DateTime> drivingDate { get; set; }
        public bool isDone { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
