//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homecare_Eksame_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DrivingPlans = new HashSet<DrivingPlan>();
        }
    
        public int employeeID { get; set; }
        public string employeeFullName { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string workSchedule { get; set; }
        public string sick { get; set; }
        public string worked { get; set; }
        public Nullable<int> userID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrivingPlan> DrivingPlans { get; set; }
        public virtual User User { get; set; }
    }
}
